/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import static Presentacion.Ganancias_Diarias.txt_doctor;
import static Presentacion.Met_Factura.Fecha;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Presentacion.MyConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static Presentacion.Met_Factura.monto;
import static Presentacion.Met_Factura.guardar;
import static Presentacion.Met_Factura.resta;
import static Presentacion.Met_Factura.suma;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;




/**
 *
 * @author PC
 */
public class Frm_factura extends javax.swing.JFrame {
    
    Calendar Fecha_Actual = new GregorianCalendar();
    DefaultTableModel tbl;

    /**
     * Creates new form Frm_factura
     */
    public Frm_factura() {
               

        initComponents();
        this.tbl = (DefaultTableModel) tbl_prod.getModel();
        Mostrardatos("");
        this.setLocationRelativeTo(null);
        getlastid();
        txt_fecha.setText(Fecha());
        
        String Info = Frm_Login.txt_usuario.getText();
            Frm_factura.txt_nombre_user.setText(Info);
            
                    ConsultarDoc(txt_doctor);

    }
    
    
    
   
    private void getlastid() {

         int lastid;
        Statement st;
        ResultSet rs;
        
         try{
            Connection con = MyConnection.getConnection();
            String sql = "select max(ID_Factura) from factura";
            st= con.createStatement();
            
            rs=st.executeQuery(sql);
            if(rs.next()){
                lastid = rs.getInt(1);
                lastid++;
                Frm_factura.txt_noFact.setText(Integer.toString(lastid));
            }
            else{
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Met_Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   

 
 
    
    
    public final void Mostrardatos(String valor){
           
            MyConnection cc=new MyConnection();
            Connection cn=MyConnection.getConnection();
          
        tbl.addColumn("ID Servicio");
            tbl.addColumn("Servicio");
            tbl.addColumn("Precio");
               tbl.addColumn("Cantidad");
     }
        
       
          public  void LimpiarTabla() {
              
               //Limpia la tabla
              
        for (int i = 0; i < tbl.getRowCount(); i++) {
            tbl.removeRow(i);
            i = i - 1;
        }
   }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_prod = new javax.swing.JTable();
        pnl_servicios = new javax.swing.JPanel();
        txt_IDServ = new javax.swing.JTextField();
        lbl_Servicio = new javax.swing.JLabel();
        txt_servicio = new javax.swing.JTextField();
        lbl_precio = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        btn_serv = new javax.swing.JButton();
        lbl_servicio = new javax.swing.JLabel();
        lbl_IDServicio = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        pnl_paciente = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        lbl_paciente = new javax.swing.JLabel();
        btn_paciente = new javax.swing.JButton();
        pnl_empleado = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        txt_nombre_user = new javax.swing.JLabel();
        lbl_fechat = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_quitar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_tipopago = new javax.swing.JLabel();
        txt_tipo_pago = new javax.swing.JComboBox<>();
        txt_doctor = new javax.swing.JComboBox<>();
        lbl_doctor = new javax.swing.JLabel();
        lbl_monto = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        lbl_total = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        new_fact = new javax.swing.JButton();
        txt_fecha = new javax.swing.JTextField();
        txt_noFact = new javax.swing.JLabel();
        btn_fact_ant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Factura");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_prod);

        pnl_servicios.setBackground(new java.awt.Color(255, 255, 255));

        txt_IDServ.setEditable(false);
        txt_IDServ.setToolTipText("");

        lbl_Servicio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_Servicio.setText("Servicio:");

        txt_servicio.setEditable(false);

        lbl_precio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_precio.setText("Precio:");

        btn_serv.setBackground(new java.awt.Color(255, 255, 255));
        btn_serv.setText("Buscar Servicio");
        btn_serv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_servActionPerformed(evt);
            }
        });

        lbl_servicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_servicio.setText("SERVICIOS");

        lbl_IDServicio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_IDServicio.setText("ID_Servicio:");

        lbl_cantidad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_cantidad.setText("Cantidad:");

        javax.swing.GroupLayout pnl_serviciosLayout = new javax.swing.GroupLayout(pnl_servicios);
        pnl_servicios.setLayout(pnl_serviciosLayout);
        pnl_serviciosLayout.setHorizontalGroup(
            pnl_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_serviciosLayout.createSequentialGroup()
                .addGroup(pnl_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_serviciosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_serviciosLayout.createSequentialGroup()
                                .addComponent(lbl_precio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_serviciosLayout.createSequentialGroup()
                                .addComponent(lbl_IDServicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_IDServ, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_serviciosLayout.createSequentialGroup()
                                .addComponent(lbl_Servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_serviciosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_cantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btn_serv))
                    .addGroup(pnl_serviciosLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lbl_servicio)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnl_serviciosLayout.setVerticalGroup(
            pnl_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_serviciosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_servicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_IDServ, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_IDServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Servicio)
                    .addComponent(txt_servicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_precio)
                    .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cantidad)
                    .addComponent(btn_serv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnl_paciente.setBackground(new java.awt.Color(255, 255, 255));

        lbl_nombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_nombre.setText("Nombre:");

        lbl_apellido.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_apellido.setText("Apellido:");

        lbl_paciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_paciente.setText("PACIENTE");

        btn_paciente.setBackground(new java.awt.Color(255, 255, 255));
        btn_paciente.setText("Buscar Paciente");
        btn_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_pacienteLayout = new javax.swing.GroupLayout(pnl_paciente);
        pnl_paciente.setLayout(pnl_pacienteLayout);
        pnl_pacienteLayout.setHorizontalGroup(
            pnl_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pacienteLayout.createSequentialGroup()
                        .addComponent(lbl_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_pacienteLayout.createSequentialGroup()
                        .addComponent(lbl_apellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_paciente)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_pacienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_paciente)
                .addGap(74, 74, 74))
        );
        pnl_pacienteLayout.setVerticalGroup(
            pnl_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_paciente)
                .addGap(13, 13, 13)
                .addGroup(pnl_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_pacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellido)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btn_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnl_empleado.setBackground(new java.awt.Color(255, 255, 255));
        pnl_empleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_usuario.setText("Usuario:");

        txt_nombre_user.setBackground(new java.awt.Color(0, 153, 0));
        txt_nombre_user.setForeground(new java.awt.Color(0, 153, 0));
        txt_nombre_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nombre_user.setText("UsuarioNom");

        javax.swing.GroupLayout pnl_empleadoLayout = new javax.swing.GroupLayout(pnl_empleado);
        pnl_empleado.setLayout(pnl_empleadoLayout);
        pnl_empleadoLayout.setHorizontalGroup(
            pnl_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_empleadoLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(pnl_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_empleadoLayout.createSequentialGroup()
                        .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_empleadoLayout.createSequentialGroup()
                        .addComponent(txt_nombre_user, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        pnl_empleadoLayout.setVerticalGroup(
            pnl_empleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_empleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nombre_user)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_fechat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_fechat.setText("Fecha:");

        btn_agregar.setBackground(new java.awt.Color(255, 255, 255));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/+.png"))); // NOI18N
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_quitar.setBackground(new java.awt.Color(255, 255, 255));
        btn_quitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/-.png"))); // NOI18N
        btn_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbl_tipopago.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_tipopago.setText("Tipo de Pago:");

        txt_tipo_pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Efectivo", "Cheque", "Tarjeta" }));

        lbl_doctor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_doctor.setText("Doctor:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_tipo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tipopago)
                            .addGap(36, 36, 36))))
                .addGap(26, 26, 26))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(lbl_doctor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_doctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_tipopago)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tipo_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        lbl_monto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_monto.setText("Monto: RD$");

        txt_monto.setEditable(false);

        lbl_total.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_total.setText("Total: RD$");

        txt_total.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FACTURACIÓN");

        btn_guardar.setBackground(new java.awt.Color(255, 255, 255));
        btn_guardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Factura No.");

        new_fact.setBackground(new java.awt.Color(255, 255, 255));
        new_fact.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        new_fact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/+_1.png"))); // NOI18N
        new_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarTabla(evt);
            }
        });

        txt_fecha.setEditable(false);
        txt_fecha.setText("YYYY/MM/DD");

        txt_noFact.setText("No");

        btn_fact_ant.setBackground(new java.awt.Color(255, 255, 255));
        btn_fact_ant.setText("FACTURAS ANTERIORES");
        btn_fact_ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fact_antActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_noFact)
                        .addGap(226, 226, 226)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(btn_fact_ant)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_servicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_monto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_total)
                                .addGap(18, 18, 18)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(new_fact)
                                .addGap(45, 45, 45))
                            .addComponent(pnl_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_fechat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_fechat)
                    .addComponent(txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_noFact))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pnl_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnl_servicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_fact_ant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnl_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_quitar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_monto)
                            .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_total)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(new_fact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_servActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_servActionPerformed
        // TODO add your handling code here:
        
          Pantalla_Serv mf = new Pantalla_Serv ();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn_servActionPerformed

    private void btn_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pacienteActionPerformed
        // TODO add your handling code here:
        
         Pantalla_Pac mf = new Pantalla_Pac ();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn_pacienteActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        //  Agrega los servicios a la tabla     

        String codserv = txt_IDServ.getText();
        String servicio = txt_servicio.getText();
        String precio = txt_precio.getText();
        String cantidad = txt_cantidad.getText();
   
         if (codserv.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Agrega El Código de Servicio");
        }
        
        else if (servicio.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Agrega El Servicio");
        }
        
        else if (precio.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Agrega El Precio");
        }
        
         else if (cantidad.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Agrega Cantidad");
        }
         
        else{
        
        monto();
         codserv = txt_IDServ.getText();
         String nombre = txt_servicio.getText();
         precio = txt_monto.getText();
        cantidad = txt_cantidad.getText();

        tbl.addRow(new Object[]{codserv,nombre,precio,cantidad});
        suma();
        
        txt_cantidad.setText("");
         }
 
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarActionPerformed
        // TODO add your handling code here:
        
        //Quita Servicios de la tabla
        
          DefaultTableModel tbll = (DefaultTableModel) tbl_prod.getModel();
        tbll.removeRow(tbl_prod.getSelectedRow());
        
        resta();
        monto();
    }//GEN-LAST:event_btn_quitarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        //Inserta la factura a la base de datos
        String nofact = txt_noFact.getText();
        String fecha = txt_fecha.getText();
        String nombre = txt_nombre.getText();
        String apellido = txt_apellido.getText();
        String codserv = txt_IDServ.getText();
        String servicio = txt_servicio.getText();
        String precio = txt_monto.getText();
        String cantidad = txt_cantidad.getText();
        String TipoPago = (String) txt_tipo_pago.getSelectedItem();
        String usuario = txt_nombre_user.getText();
   
        
         if(nofact.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega Número de Factura");
        }
        
        
        else if(fecha.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega la Fecha");
        }      
        
        else if (nombre.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Agrega El Nombre");
        }
        
        else if (apellido.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Agrega El Apellido");
        }
        
        else if (codserv.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Agrega El Código de Servicio");
        }
        
        else if (servicio.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Agrega El Servicio");
        }
        
        else if (precio.equals(""))
        {
           JOptionPane.showMessageDialog(null, "Agrega El Precio");
        }
        
        else if (usuario.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Escribe Usuario Que Atendió");
        }
         
        else if (TipoPago.equals("-"))
        {
           JOptionPane.showMessageDialog(null, "Agrega Tipo de Pago");
        }
        else{
        
        
         String detalle = txt_noFact.getText();
    for (int i=0; i<tbl.getRowCount();i++){
        
        PreparedStatement ps;
        String query = "INSERT INTO `detalle_factura`(`ID_detalle_Fact`,`ID_Servicio`, `Servicio`,`Precio`,`Cantidad`,`id_factura`) VALUES (?,?,?,?,?,?)";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
              
            ps.setString(1, detalle);
    
          ps.setString(2, tbl_prod.getValueAt(i, 0).toString());
          ps.setString(3, tbl_prod.getValueAt(i, 1).toString());
          ps.setString(4, tbl_prod.getValueAt(i, 2).toString());
          ps.setString(5, tbl_prod.getValueAt(i, 3).toString());
          ps.setString(6, detalle);
     
            if(ps.executeUpdate() > 0)
            {
            }
              
                 
        } catch (SQLException ex) {
            Logger.getLogger(Frm_Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
 
    }
        guardar();
        imprimir();
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void LimpiarTabla(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarTabla
        // Limpia el formulario para hacer una nueva factura
        
        LimpiarTabla();
        getlastid();
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_IDServ.setText("");
        txt_servicio.setText("");
        txt_precio.setText("");
        txt_cantidad.setText("");
        txt_tipo_pago.setSelectedIndex(0);
        txt_monto.setText("");
        txt_total.setText("");
        
    }//GEN-LAST:event_LimpiarTabla

    private void btn_fact_antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fact_antActionPerformed
        // TODO add your handling code here:
         FacturasAlmacenadas mf = new FacturasAlmacenadas ();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_fact_antActionPerformed

    public void imprimir(){
     
      Connection cn=MyConnection.getConnection();
        try{
            int txtFac;
          JasperReport jr = (JasperReport) JRLoader.loadObject(Frm_factura.class.getResource("/Reportes/factura.jasper"));
          Map parametros = new HashMap<>();
          parametros.put("Factura",txtFac = Integer.parseInt(txt_noFact.getText()));
          JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
          JasperViewer jv = new JasperViewer(jp, false);
          jv.setVisible(true); 
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        
     
 } 
     
    
    
    public void ConsultarDoc(JComboBox Doctor){
       String sql = "select * from vista_doc;";
       try{
         
           MyConnection cn = new MyConnection();
           Connection con;
           PreparedStatement ps;
           ResultSet rs;
           
           con = cn.getConnection();
           ps = con.prepareStatement(sql);
           rs=ps.executeQuery();
           while(rs.next()) {
               Doctor.addItem(rs.getString("Nombres"));
           }
           
           
           
       } catch (SQLException e){
           System.out.println(e.toString());
       }
   }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_fact_ant;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_paciente;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JButton btn_serv;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_IDServicio;
    private javax.swing.JLabel lbl_Servicio;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_doctor;
    private javax.swing.JLabel lbl_fechat;
    private javax.swing.JLabel lbl_monto;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_paciente;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_servicio;
    private javax.swing.JLabel lbl_tipopago;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JButton new_fact;
    private javax.swing.JPanel pnl_empleado;
    private javax.swing.JPanel pnl_paciente;
    private javax.swing.JPanel pnl_servicios;
    public static javax.swing.JTable tbl_prod;
    public static javax.swing.JTextField txt_IDServ;
    public static javax.swing.JTextField txt_apellido;
    public static javax.swing.JTextField txt_cantidad;
    public static javax.swing.JComboBox<String> txt_doctor;
    public static javax.swing.JTextField txt_fecha;
    public static javax.swing.JTextField txt_monto;
    public static javax.swing.JLabel txt_noFact;
    public static javax.swing.JTextField txt_nombre;
    public static javax.swing.JLabel txt_nombre_user;
    public static javax.swing.JTextField txt_precio;
    public static javax.swing.JTextField txt_servicio;
    public static javax.swing.JComboBox<String> txt_tipo_pago;
    public static javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

}
