/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Frm_empleados extends javax.swing.JFrame {
DefaultTableModel Empleados;
    /**
     * Creates new form Frm_empleados
     */
    public Frm_empleados() {
        initComponents();
          this.Empleados = (DefaultTableModel) tbl_emp.getModel();
        Mostrardatos("");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_cedula1 = new javax.swing.JLabel();
        jPanel_contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_insertar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        lbl_registro_pacientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_emp = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_apellido = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        lbl_cedula = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        lbl_telefono = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        lbl_direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        lbl_cargo = new javax.swing.JLabel();
        txt_cargo = new javax.swing.JTextField();
        btn_eliminar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();

        lbl_cedula1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lbl_cedula1.setText("Cédula:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control de Empleados");
        setResizable(false);

        jPanel_contenido.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo Consultorio Dental Azul Pastel.png"))); // NOI18N

        btn_insertar.setBackground(new java.awt.Color(255, 255, 255));
        btn_insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/insert.png"))); // NOI18N
        btn_insertar.setText("INSERTAR");
        btn_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertarActionPerformed(evt);
            }
        });

        btn_limpiar.setBackground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        lbl_registro_pacientes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_registro_pacientes.setText("CONTROL DE EMPLEADOS");

        tbl_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_empMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_emp);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_nombre.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lbl_nombre.setText("Nombre:");

        txt_nombre.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombreKeyPressed(evt);
            }
        });

        lbl_apellido.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lbl_apellido.setText("Apellido:");

        txt_apellido.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbl_cedula.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lbl_cedula.setText("Cédula:");

        txt_cedula.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbl_telefono.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lbl_telefono.setText("Teléfono:");

        txt_telefono.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbl_direccion.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lbl_direccion.setText("Dirección:");

        txt_direccion.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        lbl_cargo.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        lbl_cargo.setText("Cargo:");

        txt_cargo.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_telefono)
                            .addComponent(lbl_direccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_telefono)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_cargo)
                        .addGap(10, 10, 10)
                        .addComponent(txt_cargo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_apellido)
                            .addComponent(lbl_nombre))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txt_apellido)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_cedula)
                        .addGap(23, 23, 23)
                        .addComponent(txt_cedula)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_apellido))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cedula)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cargo)
                    .addComponent(txt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btn_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_actualizar.setBackground(new java.awt.Color(255, 255, 255));
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update.png"))); // NOI18N
        btn_actualizar.setText("ACTUALIZAR");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_contenidoLayout = new javax.swing.GroupLayout(jPanel_contenido);
        jPanel_contenido.setLayout(jPanel_contenidoLayout);
        jPanel_contenidoLayout.setHorizontalGroup(
            jPanel_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_contenidoLayout.createSequentialGroup()
                .addGroup(jPanel_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_contenidoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_contenidoLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_contenidoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_contenidoLayout.createSequentialGroup()
                        .addComponent(lbl_registro_pacientes)
                        .addGap(238, 238, 238))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_contenidoLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btn_limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_insertar)
                .addGap(18, 18, 18)
                .addComponent(btn_actualizar)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel_contenidoLayout.setVerticalGroup(
            jPanel_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_contenidoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_contenidoLayout.createSequentialGroup()
                        .addComponent(lbl_registro_pacientes)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_contenidoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void Limpiar(){
        try{
     txt_nombre.setText("");
     txt_apellido.setText("");
     txt_cedula.setText("");
     txt_telefono.setText("");
     txt_direccion.setText("");
     txt_cargo.setText("");

        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error "+ex);
    }
    }
    
    public void RefrescarTabla(){
        try{
            
            Empleados.setColumnCount(0);
            Empleados.setRowCount(0);
            tbl_emp.revalidate();
        }
         catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error "+ex);
        
    }
    }
    
    public final void Mostrardatos(String valor){
            //Funcion para llenar la jtable de Usuarios desde la BD
            MyConnection cc=new MyConnection();
            Connection cn=MyConnection.getConnection();
            RefrescarTabla();
            Empleados.addColumn("ID Empleado");
            Empleados.addColumn("Nombre");
            Empleados.addColumn("Apellido");
            Empleados.addColumn("Cedula");
            Empleados.addColumn("Telefono");
            Empleados.addColumn("Direccion");
            Empleados.addColumn("Cargo");



            this.tbl_emp.setModel(Empleados);
            String sql;
            if (valor.equals(""))
            {
            sql="SELECT * FROM empleados";
            }
            else{
            sql="SELECT * FROM empleados WHERE Nombre like '%"+valor+"%'";
            } 

            String []datos=new String [7];
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            datos[6]=rs.getString(7);



            Empleados.addRow(datos);
            }
            tbl_emp.setModel(Empleados);


            }catch(SQLException ex){
            Logger.getLogger(frm_Main.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
    
    
    public boolean revisarUsuarios(String usuarios) {
            PreparedStatement ps;
            ResultSet rs;
            boolean revisar = false;
            String query = "SELECT * FROM `empleados` WHERE `Nombre` = ?";
            
            try {
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, usuarios);
                
                rs = ps.executeQuery();
                
                if (rs.next())
                {
                    revisar = true;
                }
            } catch (SQLException ex) {
            Logger.getLogger(Frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
        return false;
        }
    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:

                String id = (String)Empleados.getValueAt(tbl_emp.getSelectedRow(),0);
        String nom = txt_nombre.getText();
        String apell = txt_apellido.getText();
        String ced = txt_cedula.getText();
        String tel = txt_telefono.getText();
        String dir = txt_direccion.getText();
        String cargo = txt_cargo.getText();

        PreparedStatement ps;
        String query = "UPDATE empleados SET Nombre=?, Apellido=?, Cedula=?, Telefono=?, Direccion=?, Cargo=? WHERE ID_Empleado=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

                        ps.setString(7, id);
            ps.setString(1, nom);
            ps.setString(2, apell);
            ps.setString(3, ced);
            ps.setString(4, tel);
            ps.setString(5, dir);
            ps.setString(6, cargo);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, " Empleado Modificado");
                            Limpiar();
                            Mostrardatos("");

        } catch (SQLException ex) {
            Logger.getLogger(frm_Main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:

                String id = (String)Empleados.getValueAt(tbl_emp.getSelectedRow(),0);

        PreparedStatement ps;
        String query = "DELETE FROM empleados WHERE ID_Empleado=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

                        ps.setString(1, id);

            if(ps.executeUpdate() > 0)
            {

                JOptionPane.showMessageDialog(null, "Empleado Eliminado");
                                Limpiar();
                                Mostrardatos("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(frm_Main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:

     Limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertarActionPerformed
        // TODO add your handling code here:

        String Nombre = txt_nombre.getText();
        String Apellido = txt_apellido.getText();
        String Cedula = txt_cedula.getText();
        String Telefono = txt_telefono.getText();
        String Direccion = txt_direccion.getText();
        String Cargo = txt_cargo.getText();

        if(Nombre.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega el Nombre del Empleado");
        }

        else if(Apellido.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega el Apellido del Empleado");
        }

        else if(Cedula.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega la Cédula del Empleado");
        }

        else if(Telefono.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega el Número de Teléfono del Empleado");
        }

        else if(Direccion.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega la Dirección del Empleado");
        }

        else if(Cargo.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Agrega el Cargo del Empleado");
        }

        else if(revisarEmpleado(Cedula))
        {
            JOptionPane.showMessageDialog(null, "Este Número de Cédula Ya Existe");
        }
        else{
            PreparedStatement ps;
            String query = "INSERT INTO `empleados`(`Nombre`,`Apellido`, `Cedula`, `Telefono`, `Direccion`, `Cargo`) VALUES (?,?,?,?,?,?)";
            try {
                ps = MyConnection.getConnection().prepareStatement(query);

                ps.setString(1, Nombre);
                ps.setString(2, Apellido);
                ps.setString(3, Cedula);
                ps.setString(4, Telefono);
                ps.setString(5, Direccion);
                ps.setString(6, Cargo);

                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "Nuevo Empleaado Agregado");
                      Limpiar();
                                Mostrardatos("");
                }

            } catch (SQLException ex) {
                Logger.getLogger(Frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
    }//GEN-LAST:event_btn_insertarActionPerformed

    private void tbl_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_empMouseClicked
        // TODO add your handling code here:'
        
         
        try {  
        String Nombre = (String) Empleados.getValueAt(tbl_emp.getSelectedRow(),1);
        String Apellido = (String) Empleados.getValueAt(tbl_emp.getSelectedRow(),2);
        String Cedula = (String) Empleados.getValueAt(tbl_emp.getSelectedRow(),3);
        String Telefono = (String) Empleados.getValueAt(tbl_emp.getSelectedRow(),4);
        String Direccion = (String) Empleados.getValueAt(tbl_emp.getSelectedRow(),5);
        String Cargo = (String) Empleados.getValueAt(tbl_emp.getSelectedRow(),6);
        


        txt_nombre.setText(Nombre);
        txt_apellido.setText(Apellido);
        txt_cedula.setText(Cedula);
        txt_telefono.setText(Telefono);
        txt_direccion.setText(Direccion);
        txt_cargo.setText(Cargo);

        }
         catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        } 
        
    }//GEN-LAST:event_tbl_empMouseClicked

    private void txt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyPressed
        // TODO add your handling code here:
        
         try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        String B = txt_nombre.getText()+"";
        Mostrardatos(B);
            }
        }
        catch (Exception ex){
        JOptionPane.showMessageDialog(null, "error "+ex);
        }
        
    }//GEN-LAST:event_txt_nombreKeyPressed

    public boolean revisarEmpleado(String emp) {
            PreparedStatement ps;
            ResultSet rs;
            boolean revisar = false;
            String query = "SELECT * FROM `empleados` WHERE `Cedula` = ?";
            
            try {
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, emp);
                
                rs = ps.executeQuery();
                
                if (rs.next())
                {
                    revisar = true;
                }
            } catch (SQLException ex) {
            Logger.getLogger(Frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
        return false;
        }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_contenido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_cargo;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_cedula1;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_registro_pacientes;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JTable tbl_emp;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cargo;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
